### ISSUE TITLE
Error on doing a git merge of branches

### ISSUE THREAD

**Issue by hayderimran7** [souravchk/dotfiles#1]
When merging a branch as a commit e.g. lets say you are on branch `develop` and want to merge `master` branch, on develop you do:
```
git merge master
```
git opens up VIM and lets you edit the branch merge commit message. Upon saving with `:wq` ,
i have seen it throwing error :
```
error: There was a problem with the editor 'vi'.
Not committing merge; use 'git commit' to complete the merge.
```
and git merge commit doesnt go through. I had to remove `~/.vimrc` to remove all vim settings and let it go through.  
Any idea why git isnt playing well with you vimrc? 
thanks

**Comment by souravchk** [comment]
@hayderimran7 I faced the same problem. I added `export EDITOR="/usr/bin/nano"` in my terminal, so that the git merge opens *nano* as the editor. I haven't investigated the real reason behind this but this hack worked.

**Comment by souravchk** [comment]
This [link](http://stackoverflow.com/questions/2596805/how-do-i-make-git-use-the-editor-of-my-choice-for-commits) would also help in that.

**Comment by hayderimran7** [comment]
thanks `git config --global core.editor /usr/bin/vim` fixed it 👍
